steps:
  # Step 1: Print a message to confirm build started
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'echo Build started on Google Cloud!']

  # Step 2: Run basic commands
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'ls -la']

  # Step 1: Print a message to confirm build started and install dependencies
  - name: 'python:3.12'
    entrypoint: 'sh'
    args: ['-c', 'echo Build started on Google Cloud! && pip install -r req/requirements.txt && python main.py']

  # Step 2: Print the build success message
  - name: 'python:3.12'
    entrypoint: 'sh'
    args: ['-c', 'ls -al']

    # Step 5: Build Docker image
  - name: 'docker'
    entrypoint: 'sh'
    args: ['-c', 'docker build -t gcr.io/$PROJECT_ID/nk:latest .']

  # Step 6: Push Docker image to Google Container Registry
  - name: 'docker'
    entrypoint: 'sh'
    args: ['-c', 'docker push gcr.io/$PROJECT_ID/nk:latest']

  # Step 3: Print the build success message
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'echo Build finished successfully!']

# Specify logging options

options:
  logging: CLOUD_LOGGING_ONLY
