steps:
  # Step 1: Print a message to confirm build started
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'echo Build started on Google Cloud!']

  # Step 2: Run basic commands
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'ls -la']

  # Install dependencies
  - name: 'python:3.12'
    entrypoint: 'sh'
    args: ['-c', 'pip install -r req/requirements.txt']

  # Run the main script
  - name: 'python:3.12'
    entrypoint: 'sh'
    args: ['-c', 'python main.py']

  # Step 3: Print the build success message
  - name: 'alpine'
    entrypoint: 'sh'
    args: ['-c', 'echo Build finished successfully!']

# Specify logging options
options:
  logging: CLOUD_LOGGING_ONLY
