apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: <DOCKER_IMAGE_TAGGED>
        ports:
        - containerPort: 5000

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-app
#   template:
#     metadata:
#       labels:
#         app: my-app
#     spec:
#       containers:
#       - name: my-app-container
#         image: <DOCKER_IMAGE_TAGGED>
#         ports:
#         - containerPort: 5000
#         volumeMounts:
#         - name: secret-vol
#           mountPath: /secrets
#           readOnly: true
#       volumes:
#       - name: secret-vol
#         secret:
#           secretName: cloud-build-secret
